few title changes for seo conflicts avoidance
castai/docs pull request #185
Opened 2022-01-26 13:40 UTC by Alstum

titles changed to reflect the content, + slack community link change to an invitation

2022-02-04 15:16 UTC, saumas requested changes

2022-02-04 15:16 UTC, saumas commented on mkdocs.yml
> +          - 'Remove CAST from EKS': getting-started/external-cluster/eks/remove-from-eks.md
`CAST` -> `CAST AI`

2022-03-25 07:31 UTC, Alstum commented
@saumas

2022-03-28 09:49 UTC, saumas approved these changes

2022-03-28 10:10 UTC, merged